version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    platform: linux/x86_64
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=student_management_liquibase
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  api:
    depends_on:
      - mysqldb
    build: ./studentmanagementsystem
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url": "jdbc:mysql://mysqldb:3306/student_management_liquibase?createDatabaseIfNotExist=true",
          "spring.datasource.username": "root",
          "spring.datasource.password": "root",
          "spring.liquibase.enabled": "true",
          "spring.liquibase.change-log": "classpath:/db/changelog/db.changelog-master.xml",
          "spring.jpa.hibernate.ddl-auto":"none",
          "spring.datasource.driver-class-name":"com.mysql.cj.jdbc.Driver"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    
volumes:
  db:
